on:
  push:
    branches: [ master ]

name: Conditional test

jobs:
  prerequisites:
    name: pre
    runs-on: ubuntu-latest
    outputs: 
      conditionOne: ${{ env.var1 }}
    
    steps:
    - name: step1
      run: echo "step1"

    - name: step2
      run: echo "step2"

    - name: setvar
      id: setvar
      env: 
        var1: tbd12345
      run: echo "setvar step"

  job2: 
    name: conditional
    runs-on: ubuntu-latest
    needs: prerequisites

    # if: needs.prerequisites.env.var1 == 'tbd12345'

    steps:
    - name: step4
      run: | 
        echo "step4"
        echo "${{ needs.prerequisites.outputs.conditionOne }}"

    - name: step5
      run: echo "step5"      